import mongoose from "mongoose";

const jobSchema = new mongoose.Schema({
  postId: { type: String, unique: true, required: true },
  employer: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  immutableCompanyId: String,
  companyName: String,
  title: String,
  role: String,
  genderNeeded: String,
  vacancies: { type: Number, min: 1, default: 1 },
  employmentType: { type: String, enum: ["fullTime", "partTime", "contract", "internship"], default: "fullTime" },
  ageRange: String,
  skills: [String],
  salary: String,
  requirements: String,
  googleMapLink: String,
  address: String,
  contactNumber: String,
  description: String,
  benefits: String,
  applicationStartDate: Date,
  applicationEndDate: Date,
  interviewStartDate: Date,
  interviewEndDate: Date,
  interviewStartTime: String,
  interviewEndTime: String,
  interviewMode: { type: String, enum: ["remote", "physical", "hybrid"] },
  interviewDetails: String,
  status: { type: String, enum: ["pending", "live", "closed", "rejected"], default: "pending" },
  closedAt: Date,
  closedReason: String,
  adminReason: String,
}, { timestamps: true });

export const Job = mongoose.model("Job", jobSchema);
