import mongoose from "mongoose";

const nearbySchema = new mongoose.Schema({
  label: String,
  distance: String,
}, { _id: false });

const roomSchema = new mongoose.Schema({
  roomId: { type: String, unique: true, required: true },
  publicId: String,
  owner: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  immutableOwnerId: String,
  propertyName: String,
  title: String,
  description: String,
  city: String,
  locality: String,
  address: String,
  mapLink: String,
  googleMapLink: String,
  landmark: String,
  rent: mongoose.Schema.Types.Mixed,
  deposit: mongoose.Schema.Types.Mixed,
  maintenance: mongoose.Schema.Types.Mixed,
  electricityIncluded: { type: Boolean, default: false },
  type: String,
  furnishing: String,
  gender: String,
  floor: mongoose.Schema.Types.Mixed,
  totalFloors: mongoose.Schema.Types.Mixed,
  areaSqft: mongoose.Schema.Types.Mixed,
  bathroom: String,
  maxOccupancy: mongoose.Schema.Types.Mixed,
  totalRooms: { type: Number, default: 1 },
  bedsPerRoom: { type: Number, default: 1 },
  occupiedOccupancy: { type: Number, default: 0 },
  availableOccupancy: { type: Number, default: 1 },
  occupancyStatus: { type: String, enum: ["available", "limited", "full"], default: "available" },
  availableFrom: mongoose.Schema.Types.Mixed,
  minStayMonths: mongoose.Schema.Types.Mixed,
  noticePeriodDays: mongoose.Schema.Types.Mixed,
  ownerName: String,
  ownerVerified: Boolean,
  ownerPublicId: String,
  ownerPhone: String,
  ownerWhatsapp: String,
  preferredContactTime: String,
  amenities: [String],
  rules: [String],
  nearby: [nearbySchema],
  roomType: String,
  photos: [mongoose.Schema.Types.Mixed],
  contactNumber: String,
  views: { type: Number, default: 0 },
  requests: { type: Number, default: 0 },
  tone: String,
  status: { type: String, enum: ["draft", "pending", "live", "rejected", "closed"], default: "pending" },
  statusReason: String,
  adminReason: String,
}, { timestamps: true });

export const Room = mongoose.model("Room", roomSchema);
