import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getSession } from "../../utils/auth.js";
import { fetchEmployerSummary } from "./employerApi.js";

export default function EmployerDashboard() {
  const session = getSession();
  const [summary, setSummary] = useState({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { async function load() { try { setSummary(await fetchEmployerSummary()); } catch (err) { setError(err.message || "Unable to load dashboard summary."); } finally { setLoading(false); } } load(); }, []);
  const stats = useMemo(() => ({ liveJobs: summary.statusCounts?.live || 0, pendingJobs: summary.statusCounts?.pending || 0, rejectedJobs: summary.statusCounts?.rejected || 0, totalApplications: summary.applicationCounts?.total || 0, shortlisted: summary.applicationCounts?.shortlisted || 0, interviews: summary.applicationCounts?.interview || 0, hired: summary.applicationCounts?.hired || 0 }), [summary]);
  const cards = [{ label: "Live jobs", value: stats.liveJobs, path: "/employer/jobs" }, { label: "Pending review", value: stats.pendingJobs, path: "/employer/jobs" }, { label: "Rejected posts", value: stats.rejectedJobs, path: "/employer/jobs" }, { label: "All applicants", value: stats.totalApplications, path: "/employer/applications" }, { label: "Shortlisted", value: stats.shortlisted, path: "/employer/applications" }, { label: "Interviews", value: stats.interviews, path: "/employer/applications" }, { label: "Hired", value: stats.hired, path: "/employer/applications" }];
  return <section className="section"><div className="section-header"><div><div className="section-label">Employer command center</div><h1 className="section-title">Welcome, {session?.user?.companyName || session?.companyName || "Employer"}</h1><p className="section-desc">Post jobs, monitor approval, manage candidates and run interviews from one hiring workspace.</p></div><Link className="btn-search" to="/post-job">Post a job</Link></div>{error ? <div className="login-error">{error}</div> : null}<div className="dashboard-grid">{cards.map((card) => <Link key={card.label} to={card.path} className="dashboard-card dashboard-card-small"><span>{card.label}</span><strong>{card.value}</strong></Link>)}</div><div className="dashboard-grid dashboard-main-grid"><div className="form-card"><div className="section-label">Hiring actions</div><p className="section-desc">Build a structured job post with vacancies, eligibility, location, map link, salary and requirements.</p><div className="quick-actions"><Link className="btn-search" to="/post-job">Create job post</Link><Link className="btn-secondary" to="/employer/jobs">View job pipeline</Link><Link className="btn-secondary" to="/employer/applications">Open applicants</Link></div></div><div className="form-card"><div className="section-label">Recent candidate responses</div>{loading ? <p className="section-desc">Loading recent activity...</p> : summary.recent?.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Candidate</th><th>Job</th><th>Status</th></tr></thead><tbody>{summary.recent.map((application) => <tr key={application._id}><td>{application.candidate?.fullName || application.candidate?.email || "Candidate"}</td><td>{application.job?.title || "-"}</td><td><span className="status-pill">{application.status}</span></td></tr>)}</tbody></table></div> : <p className="section-desc">No applications yet. Your responses will appear here once candidates show interest.</p>}</div></div></section>;
}
